### ISSUE TITLE
Handle uncaught exceptions when getting/setting

### ISSUE THREAD

**Issue by emuvente** [kiva/WebStorage#2]
When using webstorage in Safari in Private mode, attempting to get or set will result in a Maximum Quota Exceeded error being thrown. We should wrap the getItem and setItem calls in a try/catch block to deal with this. When there is an error, returning undefined seems like a reasonable response.

**Comment by jedlin-kiva** [comment]
For getItem, consider an optional second parameter containing a default value (e.g. an empty object) to return if getItem fails.

For setItem, the appropriate return seems a boolean "succeess" value.

**Comment by emuvente** [comment]
I think those would be extra features we could consider. To handle this issue, I think we should make it as invisible as possible. Just returning undefined in the get case allows it to be treated as if the value didn't exist. And we currently don't return anything in the set case.
